server:
 port: 8118
dubbo:
  application:
    name: lk-project-marketing-api
    owner: bill
    logger: slf4j
  registry:
    address: zookeeper://120.46.151.254:2181
    protocol: zookeeper
    check: false
    subscribe: true
    timeout: 60000
    group: dubbo
  monitor:
    protocol: registry
  protocol:
    name: dubbo
    port: 20880
    threadpool: fixed
    threads: 100
    accepts: 1000
    charset: UTF-8
    dispatcher: all
    payload: 104857600
    timeout: 60000
    check: false
    token: false
  provider:
    timeout: 60000
    check: false
    token: false
  consumer:
    timeout: 60000
    check: false

