
# not working, moved to jenkin config
spring:
  application:
    name: marketing-rds
  datasource:
    url: jdbc:mysql://120.46.151.254:13306/coupon?characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: coupon
    password: coupon

   #数据库连接池配置
    max-active: 200
    max-idle: 100
    min-idle: 50
    initial-size: 20
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    validation-query: select 1
    #每10分钟收集空闲连接，单位毫秒
    time-between-eviction-runs-millis: 600000
    #连接的最大空闲时间，单位毫秒，60分钟
    min-evictable-idle-time-millis: 3600000
    max-wait: 60000
  flyway:
    locations: classpath:db/migration
    #如果数据库不是空表，需要设置成true,否则启动报错
    baseline-on-migrate: true
    #验证错误时，是否自动清除数据库
    clean-on-validation-error: false
    #如果启动时需要flyway管理sql脚本，则设置true
    enabled: true






